import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ✨ NextAuth 대신, Next.js 자체 쿠키 저장소와 jsonwebtoken을 가져옵니다.
import { cookies } from "next/headers";
import jwt from "jsonwebtoken"; 
import { UserInitializer } from "@/components/UserInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  // 1. 브라우저가 보낸 쿠키에서 "accessToken"을 꺼냅니다.
  const cookieStore = await cookies();
  const token = cookieStore.get("accessToken")?.value;

  let user = null;

  // 2. 토큰이 있다면 암호를 풀어서(verify) 유저 정보를 추출합니다.
  if (token) {
    try {
      // route.ts에서 토큰을 만들 때 사용했던 JWT_SECRET과 똑같은 키로 풉니다.
      const decoded = jwt.verify(token, process.env.JWT_SECRET || "");
      
      // 토큰 안에 들어있던 데이터를 객체로 묶어줍니다.
      user = {
        id: (decoded as any).id,
        email: (decoded as any).email,
        nickname: (decoded as any).nickname,
      };
    } catch (err) {
      console.error("토큰이 만료되었거나 유효하지 않습니다:", err);
      // 토큰이 잘못되었다면 user는 null로 유지됩니다.
    }
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 3. 해독된 진짜 유저 정보를 UserInitializer를 통해 Zustand로 넘겨줍니다! */}
        <UserInitializer user={user} />
        {children}
      </body>
    </html>
  );
}